name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_TON_API_KEY: ${{ secrets.VITE_TON_API_KEY }}
          VITE_TON_ENDPOINT: https://api.ton.cat/v2
          VITE_MANIFEST_URL: https://ivxx420.github.io/Giftfarm/ton-connect-manifest.json
          VITE_API_URL: https://ivxx420.github.io/api

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 